"""ES/PT/TR/UK content for childrens_matrix.py (TZ-116, TZ-080 pattern).

Shape: {lang: {key: {field: value}}} — see app.core.structural_i18n.
- CHILD_ARCANA_I18N: key is the arcana number as a string ("1".."22");
  fields are strength, support.

Generated by scripts/generate_structural_translations.py --section
childrens_matrix. Empty until that runs; pick() falls back to English for
any language not present here yet.
"""

CHILD_ARCANA_I18N: dict[str, dict[str, dict[str, str]]] = {}
