"""ES/PT/TR/UK content for destiny_matrix.py (TZ-101, TZ-080 pattern).

Shape: {lang: {key: {field: value}}} — see app.core.structural_i18n.
- ARCANA_MATRIX_I18N: key is the arcana number as a string ("1".."22");
  fields are light, shadow.

Arcana *names* are deliberately not duplicated here — seo_i18n.TAROT_MAJOR_I18N
already carries all 22 in every language, and destiny_matrix.arcana_name()
reads them straight from there.

Generated by scripts/generate_structural_translations.py --section
destiny_matrix. Empty until that runs; pick() falls back to English for any
language not present here yet.
"""

ARCANA_MATRIX_I18N: dict[str, dict[str, dict[str, str]]] = {}
