"""ES/PT/TR/UK content for karmic_tail.py (TZ-114, TZ-080 pattern).

Shape: {lang: {key: {field: value}}} — see app.core.structural_i18n.
- KARMIC_TAIL_I18N: key is the tail code ("t1-t2-t3", e.g. "12-19-7");
  fields are name, essence, task.

Generated by scripts/generate_structural_translations.py --section
karmic_tail. Empty until that runs; pick() falls back to English for any
language not present here yet.
"""

KARMIC_TAIL_I18N: dict[str, dict[str, dict[str, str]]] = {}
