"""ES/PT/TR/UK content for money_line.py (TZ-115, TZ-080 pattern).

Shape: {lang: {key: {field: value}}} — see app.core.structural_i18n.
- MONEY_ENERGY_I18N: key is the arcana number as a string ("1".."22");
  fields are flow, block.

Generated by scripts/generate_structural_translations.py --section
money_line. Empty until that runs; pick() falls back to English for any
language not present here yet.
"""

MONEY_ENERGY_I18N: dict[str, dict[str, dict[str, str]]] = {}
