export const TIMEZONES = [
  { key: "kaliningrad", offset: "UTC+2", value: "Europe/Kaliningrad" },
  { key: "moscow", offset: "UTC+3", value: "Europe/Moscow" },
  { key: "samara", offset: "UTC+4", value: "Europe/Samara" },
  { key: "yekaterinburg", offset: "UTC+5", value: "Asia/Yekaterinburg" },
  { key: "omsk", offset: "UTC+6", value: "Asia/Omsk" },
  { key: "krasnoyarsk", offset: "UTC+7", value: "Asia/Krasnoyarsk" },
  { key: "irkutsk", offset: "UTC+8", value: "Asia/Irkutsk" },
  { key: "yakutsk", offset: "UTC+9", value: "Asia/Yakutsk" },
  { key: "vladivostok", offset: "UTC+10", value: "Asia/Vladivostok" },
  { key: "magadan", offset: "UTC+11", value: "Asia/Magadan" },
  { key: "kamchatka", offset: "UTC+12", value: "Asia/Kamchatka" },
  { key: "kyiv", offset: "UTC+2/3", value: "Europe/Kyiv" },
  { key: "minsk", offset: "UTC+3", value: "Europe/Minsk" },
  { key: "almaty", offset: "UTC+5", value: "Asia/Almaty" },
  { key: "tashkent", offset: "UTC+5", value: "Asia/Tashkent" },
  { key: "london", offset: "UTC+0/1", value: "Europe/London" },
  { key: "berlin", offset: "UTC+1/2", value: "Europe/Berlin" },
  { key: "dubai", offset: "UTC+4", value: "Asia/Dubai" },
  { key: "bangkok", offset: "UTC+7", value: "Asia/Bangkok" },
  { key: "new_york", offset: "UTC-5/-4", value: "America/New_York" },
  { key: "los_angeles", offset: "UTC-8/-7", value: "America/Los_Angeles" },
];
