export const TIMEZONES = [
  { label: "Калининград (UTC+2)", value: "Europe/Kaliningrad" },
  { label: "Москва (UTC+3)", value: "Europe/Moscow" },
  { label: "Самара (UTC+4)", value: "Europe/Samara" },
  { label: "Екатеринбург (UTC+5)", value: "Asia/Yekaterinburg" },
  { label: "Омск (UTC+6)", value: "Asia/Omsk" },
  { label: "Красноярск (UTC+7)", value: "Asia/Krasnoyarsk" },
  { label: "Иркутск (UTC+8)", value: "Asia/Irkutsk" },
  { label: "Якутск (UTC+9)", value: "Asia/Yakutsk" },
  { label: "Владивосток (UTC+10)", value: "Asia/Vladivostok" },
  { label: "Магадан (UTC+11)", value: "Asia/Magadan" },
  { label: "Камчатка (UTC+12)", value: "Asia/Kamchatka" },
  { label: "Киев (UTC+2/3)", value: "Europe/Kyiv" },
  { label: "Минск (UTC+3)", value: "Europe/Minsk" },
  { label: "Алматы (UTC+5)", value: "Asia/Almaty" },
  { label: "Ташкент (UTC+5)", value: "Asia/Tashkent" },
  { label: "Лондон (UTC+0/1)", value: "Europe/London" },
  { label: "Берлин (UTC+1/2)", value: "Europe/Berlin" },
  { label: "Дубай (UTC+4)", value: "Asia/Dubai" },
  { label: "Бангкок (UTC+7)", value: "Asia/Bangkok" },
  { label: "Нью-Йорк (UTC-5/-4)", value: "America/New_York" },
  { label: "Лос-Анджелес (UTC-8/-7)", value: "America/Los_Angeles" },
];
