"""Shared lookup helpers for the TZ-080 structural-data i18n pattern.

Every section keeps its canonical ru/en values inline in its own data dict
(e.g. RUNES[i]["meaning_ru"]/["meaning_en"]) — those never move. es/pt/tr/uk
values live in a companion `<section>_i18n.py` module, always shaped
{lang: {key: {field: value}}}, generated by
scripts/generate_structural_translations.py. A (lang, key, field) triple
missing from that module — not yet translated, or the generation pass hasn't
run at all — falls back to the English value rather than raising or silently
reverting to Russian, so a partial translation pass never breaks a response.
"""


def localized_field(i18n_module: dict, lang: str, key: str, field: str, en_value: str) -> str:
    return i18n_module.get(lang, {}).get(key, {}).get(field) or en_value


def pick(base: dict, field: str, lang: str, i18n_module: dict | None = None, key: str | None = None) -> str:
    """Select `field` from a dict that always has `{field}_ru`/`{field}_en`,
    with an optional i18n_module (keyed by `key`) for es/pt/tr/uk."""
    if lang == "ru":
        return base[f"{field}_ru"]
    en_value = base[f"{field}_en"]
    if lang == "en" or i18n_module is None or key is None:
        return en_value
    return localized_field(i18n_module, lang, key, field, en_value)
